[workspace]
resolver = "3"
members = [
    "crates/sunk-app",
    "crates/sunk-core",
    "crates/sunk-desktop",
    "crates/sunk-filesystem",
    "crates/sunk-renderer",
    "crates/sunk-settings",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.87"
license = "GPL-3.0-only"
repository = "https://github.com/MajoIreina/Sunk"

[workspace.dependencies]
sunk-core = { path = "crates/sunk-core" }
sunk-desktop = { path = "crates/sunk-desktop" }
sunk-filesystem = { path = "crates/sunk-filesystem" }
sunk-renderer = { path = "crates/sunk-renderer" }
sunk-settings = { path = "crates/sunk-settings" }
bytemuck = { version = "1.25.0", features = ["derive"] }
pollster = "0.4.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "0.9.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
trash = { version = "5.2.6", default-features = false, features = ["coinit_apartmentthreaded"] }
wgpu = { version = "30.0.0", default-features = false, features = ["std", "parking_lot", "dx12", "metal", "wgsl"] }
winit = "=0.30.13"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
