[package]
name = "sunk-renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sunk-core.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
wgpu.workspace = true
winit.workspace = true

[lints]
workspace = true
