[package]
name = "sunk-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
sunk-core.workspace = true
sunk-desktop.workspace = true
sunk-renderer.workspace = true
sunk-settings.workspace = true
pollster.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
winit.workspace = true

[lints]
workspace = true

[[bin]]
name = "sunk"
path = "src/main.rs"
